Lecture 24 to 26 - WebDev/Web/Models/Assignment.cs
namespace Web.Models
{
    public class Assignment
    {
        public int Id { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedTo { get; set; }
        public Assignment(int id, string createdBy, string assignedTo)
        {
            Id = id;
            CreatedBy = createdBy;
            AssignedTo = assignedTo;
        }

        public Assignment()
        {
             
        }
    }
}

Lecture 24 to 26 - WebDev/Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lecture 24 to 26 - WebDev/Web/Models/ToDoTask.cs
namespace Web.Models
{
    public class ToDoTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedOn { get; set; }
        public bool? Done { get; set; }
        public int AssignmentId { get; set; }
        public Assignment Assignment { get; set; }

        public ToDoTask(int id, string name, string description, DateTime createdOn, bool? done, int assignmentId)
        {
            Id = id;
            Name = name;
            CreatedOn = createdOn;
            Done = done;
            AssignmentId = assignmentId;
        }
        
        public ToDoTask()
        {
        }
    }
}

Lecture 24 to 26 - WebDev/Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lecture 24 to 26 - WebDev/Web/Controllers/TaskController.cs
using Microsoft.AspNetCore.Mvc;
using Web.Entity.Models;
using Web.Services;

namespace Web.Controllers
{
    public class TaskController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            using TaskService taskService = new();

            var tasks = taskService.GetAllTasks();

            return View(tasks);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ToDoTasks task)
        {
            if (task == null)
            {
                return BadRequest();
            }

            ToDoTasks newTask = new ToDoTasks();

            newTask.Name = task.Name;
            newTask.DateCreated = task.DateCreated;
            newTask.Done = task.Done;
            newTask.Assignment = new Assignments()
            {
                AssignedTo = task.Assignment.AssignedTo,
                CreatedBy = task.Assignment.CreatedBy
            };

            using TaskService taskService = new();
            taskService.CreateTask(newTask);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            using TaskService tasksService = new();
            var taskDetails = tasksService.GetDetails(id);

            return View(taskDetails);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            using TaskService taskService = new();
            var currentTask = taskService.ShowTask(id);
            return View(currentTask);
        }

        [HttpPost]
        public IActionResult Edit(ToDoTasks data)
        {
            using TaskService taskService = new();
            taskService.Update(data);
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            using TaskService taskService = new();
            taskService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}


Lecture 24 to 26 - WebDev/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lecture 24 to 26 - WebDev/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Task" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lecture 24 to 26 - WebDev/Web/Views/Task/Create.cshtml
@model Web.Entity.Models.ToDoTasks

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">

            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div>
                <label asp-for="DateCreated"></label>
                <input asp-for="DateCreated" class="form-control" />
            </div>
            <div>
                <label asp-for="Assignment.CreatedBy"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div>
                <label asp-for="Assignment.AssignedTo"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div>
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Lecture 24 to 26 - WebDev/Web/Views/Task/Details.cshtml
@model Web.Entity.Models.ToDoTasks

@{
    ViewData["Title"] = "Details";
}

<h1>Task Details</h1>

<section>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AssignmentId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AssignmentId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Done)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Done)
        </dd>
    </dl>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</section>

Lecture 24 to 26 - WebDev/Web/Views/Task/Edit.cshtml
@model Web.Entity.Models.ToDoTasks

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Task</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div>
                <input asp-for="Id" class="form-control" type="hidden" />
            </div>

            <div>
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div>
                <label asp-for="DateCreated"></label>
                <input asp-for="DateCreated" class="form-control" />
            </div>
            <div>
                <label asp-for="Assignment.CreatedBy"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div>
                <label asp-for="Assignment.AssignedTo"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div>
                <label asp-for="Done"></label>
                <input asp-for="Done" class="form-control" />
            </div>
            <div>
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Task</a>
</div>

Lecture 24 to 26 - WebDev/Web/Views/Task/Index.cshtml
@model IEnumerable<Web.Entity.Models.ToDoTasks>

<h1>To Do List</h1>

<div>
    <a asp-action="Create">New task</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assignment.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assignment.AssignedTo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Done)
            </th>
            <th>
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var task in Model)
        {
            <tr>
                <td>
                    @task.Id
                </td>
                <td>
                    @task.Name
                </td>
                <td>
                    @task.DateCreated
                </td>
                <td>
                    @task.Assignment.CreatedBy
                </td>
                <td>
                    @task.Assignment.AssignedTo
                </td>
                <td>
                    @task.Done
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@task.Id">Edit</a>
                    |
                    <a asp-action="Details" asp-route-id="@task.Id">Details</a>
                    |
                    <a asp-action="Delete" asp-route-id="@task.Id">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>
